architecture: YOLOv5
norm_type: sync_bn
use_ema: True
ema_decay: 0.9999
ema_decay_type: "exponential"
act: silu
find_unused_parameters: True

depth_mult: 1.0
width_mult: 1.0

YOLOv5:
  backbone: EfficientRep
  neck: RepPANNeck
  yolo_head: EffiDeHead
  post_process: ~

EfficientRep:
  return_idx: [1, 2, 3]
  depthwise: false

RepPANNeck:
  depthwise: false

EffiDeHead:
  depthwise: false
  assigner:
    name: SimOTAAssigner
    candidate_topk: 10
    use_vfl: False
  nms:
    name: MultiClassNMS
    nms_top_k: 10000
    keep_top_k: 300
    score_threshold: 0.001
    nms_threshold: 0.65
