_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_300e_high.yml',
  '_base_/yolov5u_cspdarknet.yml',
  '_base_/yolov5u_reader_high_aug.yml',
]
depth_mult: 1.0
width_mult: 1.0


log_iter: 100
snapshot_epoch: 10
weights: output/yolov5u_l_300e_coco/model_final


TrainReader:
  batch_size: 16 # default 8 gpus, total bs = 128
