_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_400e.yml',
  '_base_/yolov6_efficientrep.yml',
  '_base_/yolov6_reader.yml',
]
depth_mult: 0.33
width_mult: 0.50

log_iter: 100
snapshot_epoch: 10
weights: output/yolov6_s_400e_coco/model_final


EffiDeHead:
  reg_max: 0
  use_dfl: False
  iou_type: 'giou'


TrainReader:
  batch_size: 32 # total batch_size = 32 * gpu_num

EvalReader:
  batch_size: 4
