_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_300e.yml',
  '_base_/yolov7.yml',
  '_base_/yolov7_reader.yml',
]
depth_mult: 1.0
width_mult: 1.0

log_iter: 100
snapshot_epoch: 10
weights: output/yolov7_tiny_416_300e_coco/model_final


ELANNet:
  return_idx: [2, 3, 4]
  depthwise: false
  arch: 'tiny'
  act: 'LeakyReLU'

ELANFPN:
  depthwise: false
  arch: 'tiny'
  act: 'LeakyReLU'


input_height: &input_height 416
input_width: &input_width 416
input_size: &input_size [*input_height, *input_width]
mosaic_epoch: &mosaic_epoch 300

worker_num: 4
TrainReader:
  sample_transforms:
    - DecodeNormResize: {target_size: *input_size, mosaic: True}
    - MosaicPerspective: {mosaic_prob: 1.0, target_size: 416}
    - RandomHSV: {hgain: 0.015, sgain: 0.7, vgain: 0.4}
    - RandomFlip: {}
    - BboxXYXY2XYWH: {}
    - NormalizeBox: {}
    - NormalizeImage: {mean: [0, 0, 0], std: [1, 1, 1], is_scale: True}
    - RGBReverse: {} # bgr->rgb
    - Permute: {}
  batch_size: 8
  shuffle: True
  drop_last: False
  use_shared_memory: False
  collate_batch: False
  mosaic_epoch: *mosaic_epoch


EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *input_size, keep_ratio: True}
    - Pad: {size: *input_size, fill_value: [114., 114., 114.]}
    - NormalizeImage: {mean: [0, 0, 0], std: [1, 1, 1], is_scale: True}
    - Permute: {}
  batch_size: 8


TestReader:
  inputs_def:
    image_shape: [3, 416, 416]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: *input_size, keep_ratio: True}
    - Pad: {size: *input_size, fill_value: [114., 114., 114.]}
    - NormalizeImage: {mean: [0, 0, 0], std: [1, 1, 1], is_scale: True}
    - Permute: {}
  batch_size: 1
  fuse_normalize: True
