_BASE_: [
  'yolov7_tiny_300e_coco.yml',
]
log_iter: 100
snapshot_epoch: 10
weights: output/yolov7_tiny_416_300e_coco/model_final


EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [416, 416], keep_ratio: True}
    - Pad: {size: [416, 416], fill_value: [114., 114., 114.]}
    - NormalizeImage: {mean: [0, 0, 0], std: [1, 1, 1], is_scale: True}
    - Permute: {}
  batch_size: 8


TestReader:
  inputs_def:
    image_shape: [3, 416, 416]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [416, 416], keep_ratio: True}
    - Pad: {size: [416, 416], fill_value: [114., 114., 114.]}
    - NormalizeImage: {mean: [0, 0, 0], std: [1, 1, 1], is_scale: True}
    - Permute: {}
  batch_size: 1
  fuse_normalize: True
