_BASE_: [
  '../datasets/coco_instance.yml',
  '../runtime.yml',
  './_base_/optimizer_300e.yml',
  './_base_/rtmdet_ins_cspnext.yml',
  './_base_/rtmdet_reader.yml',
]
depth_mult: 0.33
width_mult: 0.50

log_iter: 100
snapshot_epoch: 10
weights: output/rtmnet_ins_s_300e_coco/model_final
pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/pretrained/cspnext_s_pretrained.pdparams
