_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_300e.yml',
  '_base_/yolov5p6_cspdarknet.yml',
  '_base_/yolov5p6_reader.yml',
]
depth_mult: 0.33
width_mult: 0.50

log_iter: 100
snapshot_epoch: 10
weights: output/yolov5p6_s_300e_coco/model_final
