_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_300e.yml',
  '_base_/yolov5_cspdarknet.yml',
  '_base_/yolov5_reader.yml',
]
depth_mult: 0.67
width_mult: 0.75

log_iter: 100
snapshot_epoch: 10
weights: output/yolov5_m_300e_coco/model_final
