# TrainReader is temporarily set the same as YOLOX' TrainReader
# EvalReader and TestReader is the final RTMDet reader

worker_num: 4
TrainReader:
  sample_transforms:
    - Decode: {}
    - Mosaic:
        prob: 1.0
        input_dim: [640, 640]
        degrees: [-10, 10]
        scale: [0.1, 2.0]
        shear: [-2, 2]
        translate: [-0.1, 0.1]
        enable_mixup: True
        mixup_prob: 1.0
        mixup_scale: [0.5, 1.5]
    - AugmentHSV: {is_bgr: False, hgain: 5, sgain: 30, vgain: 30}
    - PadResize: {target_size: 640}
    - RandomFlip: {}
  batch_transforms:
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - PadGT: {}
  batch_size: 32
  shuffle: True
  drop_last: True
  use_shared_memory: True
  collate_batch: True
  mosaic_epoch: 280


EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: True, interp: 1}
    - Pad: {size: [640, 640], fill_value: [114., 114., 114.]}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1


TestReader:
  inputs_def:
    image_shape: [3, 640, 640]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: True, interp: 1}
    - Pad: {size: [640, 640], fill_value: [114., 114., 114.]}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1
  fuse_normalize: False
